"""mistake in filed of auidoresult

Revision ID: f56525d99de6
Revises: 107261008b17
Create Date: 2025-05-27 21:32:59.111242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f56525d99de6'
down_revision: Union[str, None] = '107261008b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audioresults', sa.Column('transcription', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('audioresults', 'transcribition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audioresults', sa.Column('transcribition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('audioresults', 'transcription')
    # ### end Alembic commands ###
